### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by Jakobud** [millercl/gulp-webdav-sync#1]
Can you show more examples of things like how to specify the user password via passing a string, how to set the folder path for where you want to sync to, etc? It's just not clear at all from your documentation...

**Comment by millercl** [comment]
Documentation is a work-in-progress. The given examples of HTTP Basic Authentication, and URL targeting have source examples and reference documentation in [README.md](https://github.com/millercl/gulp-webdav-sync/blob/master/README.md) since [0.3.1](https://github.com/millercl/gulp-webdav-sync/commit/edbf881be51ff20a67f257a4a88fead1465a132c). There are also two recipes - `gulp.watch` and  [gulp-watch](https://github.com/floatdrop/gulp-watch) for "real-time" synchronization since [0.3.5](https://github.com/millercl/gulp-webdav-sync/releases/tag/0.3.5). May reopen for more-specific difficulties. New use-cases would be appreciated as separate issues.
