### ISSUE TITLE
Use with BrowserSync

### ISSUE THREAD

**Issue by gregorskii** [millercl/gulp-webdav-sync#9]
Hi there,

Do you have any recommendations for how to use this with browserSync?

It appears that this plugin does not expose a stream back from piping to:

```
.pipe(plugins.webdavSync(options))
```

Where one could attach a streaming reload to browserSync.

I have tried these attempts:

```
return plugins.watch('WATCH GLOB')
      .pipe(plugins.webdavSync(options)
        .on('finish', function() {
          console.log('finished uploading!');
        })
      )
    ;
```

```
return plugins.watch('WATCH GLOB')
      .pipe(plugins.webdavSync(options))
      .on('finish', function() {
        console.log('finished uploading!');
      })
    ;
```

```
return plugins.watch('WATCH GLOB')
      .pipe(plugins.webdavSync(options))
      .on('end', plugins.browserSync.reload)
    ;
```

```
return plugins.watch('WATCH GLOB')
      .pipe(plugins.webdavSync(options))
      .pipe(plugins.browserSync.stream({ reload: true })
    ;
```

It looks like the plugin returns the stream:

https://github.com/millercl/gulp-webdav-sync/blob/master/index.js#L353

But it does not appear to respond to any of the .on events. I am assuming one would attach directly to the `plugins.webdavSync(options)` function call as that is what is returning the stream, but I am not sure if pipe would return that?

I have tried this using https://github.com/ThierrySpetebroot/gulp-fn:

```
return plugins.watch('WATCH GLOB')
      .pipe(plugins.fn(function() {
        console.log('WAT');
      }))
      .pipe(plugins.webdavSync(options))
    ;
```

And I get the correct output:

```
WAT
[gulp-webdav-sync] 204 /scripts/app.js
```

But the stream after this plugin does not trigger the console message:

```
return plugins.watch('WATCH GLOB')
      .pipe(plugins.webdavSync(options))
      .pipe(plugins.fn(function() {
        console.log('WAT');
        // plugins.browserSync.reload();
      }))
    ;
```

No console out.

What do you think?

**Comment by millercl** [comment]
`gulp-watch` pushes vinyl objects on change. It won’t push for files that are already present; use `gulp.src()` for that, or try creating a file after the task has started.
```js
gulp.task( 'deploy', function () {
  return gulp.src( paths.js )
    .pipe( plugins.watch( paths.js ) )
    .pipe( pulgins.webdavSync( href ) )
} )
```
The [close()](https://www.npmjs.com/package/gulp-watch#methods) method should cause a `finish` event, otherwise it shouldn’t be expected on an endless stream. Did you try any events other than `finish` and `end`? There is some test coverage for stream events. [The only call to `stream.emit()` is for errors.](https://github.com/millercl/gulp-webdav-sync/blob/4f3a8bf10d8819329f1ea3756cb4f398256f4724/index.js#L552) [There are three units tests for `'error'` events.](https://github.com/millercl/gulp-webdav-sync/blob/4f3a8bf10d8819329f1ea3756cb4f398256f4724/test/test.js#L117-L231) [There is one listener for `'finish'` events.](https://github.com/millercl/gulp-webdav-sync/blob/4f3a8bf10d8819329f1ea3756cb4f398256f4724/index.js#L347-L352) There are no unit tests for the finish event, but it shows up in the integration test (`gulp int-test`). [It should be emitted when the source calls `end()`.](https://nodejs.org/api/stream.html#stream_events_finish_and_end)

In all versions through [v1.0.3](https://github.com/millercl/gulp-webdav-sync/releases/tag/v1.0.3), the plugin consumes the [vinyl](https://github.com/gulpjs/vinyl) objects in the stream upon processing (uploading) them. _i.e._, they will not be written, pushed, or piped downstream. A stream is always returned, but file handles within are consumed. You can examine the presence and path of the vinyl objects using [gulp-debug](https://github.com/sindresorhus/gulp-debug), which is [called in this project’s `gulpfile.js`](https://github.com/millercl/gulp-webdav-sync/blob/4f3a8bf10d8819329f1ea3756cb4f398256f4724/gulpfile.js#L19). After cloning the project, set the destination server (which could alternately be a project `.npmrc` in the same directory), and run the integration test.

```shell
git clone https://github.com/millercl/gulp-webdav-sync.git gws
cd gws
npm set dav "http://dav:dav@localhost:8890/DAV/int/"
gulp int-test
```
```
[12:24:09] Using gulpfile ~/gws/gulpfile.js
[12:24:09] Starting '.npmrc'...
[12:24:09] Finished '.npmrc' 
[12:24:09] Starting 'int-test'...
[gulp-webdav-sync] http://localhost:8890/DAV/int/
[gulp-webdav-sync] 200 dir/
[gulp-webdav-sync] 200 file.txt
[gulp-webdav-sync] 200 dir/file.txt
[12:24:10] post 0 items
[12:24:10] Finished 'int-test'
```
Zero items are expected because they were all uploaded. Other gulp plugins update the [`vinyl.path`](https://github.com/gulpjs/vinyl#optionspath) when creating or moving a file. The sense in which this plugin should change the path is from an absolute file path to a URL. Setting `vinyl.path` to a URL is undefined and unsupported, [vinyl-fs](https://github.com/gulpjs/vinyl-fs) is an adapter for the file system, hence the decision to consume the `vinyl` objects rather than [`push()`](https://nodejs.org/api/stream.html#stream_readable_push_chunk_encoding) them. That said, no functionality is gained by consuming rather than pushing, and improving BrowserSync integration is within the project’s scope.

**Comment by gregorskii** [comment]
Using this config:

```
return gulp.src(`PATHS/**`)
      .pipe(plugins.watch(
        `PATHS/**`,
        { ignoreInitial: true }
      ))
      .pipe(plugins.webdavSync(options))
      .pipe(plugins.fn(() => {
        plugins.browserSync.reload();
      }))
    ;
```

I get this error:

```
[gulp-webdav-sync] 405 PROJECT/
[gulp-webdav-sync] 204 PROJECT/js.txt
[gulp-webdav-sync] 405 PROJECT/components/
[gulp-webdav-sync] 204 PROJECT/jsMap.txt
[gulp-webdav-sync] 405 PROJECT/install/
[gulp-webdav-sync] 405 PROJECT/scripts/
[gulp-webdav-sync] 405 PROJECT/templates/
[gulp-webdav-sync] 204 PROJECT/scripts/1.js
[gulp-webdav-sync] 405 PROJECT/components/COMPONENT1/
[gulp-webdav-sync] 405 PROJECT/components/COMPONENT2/
[gulp-webdav-sync] 405 PROJECT/components/COMPONENT3/
[gulp-webdav-sync] 204 PROJECT/scripts/2.js
[gulp-webdav-sync] 405 PROJECT/templates/base/

PROJECT/web/node_modules/sax/lib/sax.js:667
    er = new Error(er)
         ^
Error: Unexpected close tag
Line: 61
Column: 11
Char: >
    at error (PROJECT/node_modules/sax/lib/sax.js:667:10)
    at strictFail (PROJECT/node_modules/sax/lib/sax.js:693:7)
    at closeTag (PROJECT/node_modules/sax/lib/sax.js:887:9)
    at Object.write (PROJECT/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (PROJECT/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (PROJECT/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseString (PROJECT/node_modules/xml2js/lib/xml2js.js:540:19)
    at IncomingMessage.<anonymous> (PROJECT/node_modules/gulp-webdav-sync/index.js:545:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Obscuring the project name with PROJECT.

I don't quite understand the notes above. I do not need to mess with the internals of the fs events that are triggered, pushed, or consumed. I need the ` .pipe(plugins.webdavSync(options))` to return a stream that is consumable by:

```
 .pipe(plugins.fn(() => {
        plugins.browserSync.reload();
      }))
```

Essentially one that allows that plugins.fn to run. Is this not possible because of the way that `vinyl-fs` is creating/consuming/returning the streams?

Thanks!

**Comment by millercl** [comment]
[v1.0.4](https://github.com/millercl/gulp-webdav-sync/releases/tag/v1.0.4) returns the vinyl objects rather than consuming them.
```shell
gulp int-test
```
```
[02:13:57] Using gulpfile ~/gws/gulpfile.js
[02:13:57] Starting '.npmrc'...
[02:13:57] Finished '.npmrc'
[02:13:57] Starting 'int-test'...
[gulp-webdav-sync] http://localhost:8890/DAV/
[gulp-webdav-sync] 200 dir/
[02:13:57] post test/assets/int/dir
[gulp-webdav-sync] 200 file.txt
[02:13:57] post test/assets/int/file.txt
[gulp-webdav-sync] 200 dir/file.txt
[02:13:57] post test/assets/int/dir/file.txt
[02:13:57] post 3 items
[02:13:57] Finished 'int-test'
```

**Comment by millercl** [comment]
```js
gulp.task( 'sync'
  , function () {
      HREF = 'http://localhost:8890/DAV/'
      browserSync.init( { proxy: HREF } )
      return gulp.src( paths.src )
        .pipe( watch( paths.src ) )
        .pipe( webdav( HREF, { log: 'info' } ) )
        .pipe( browserSync.stream() )
    }
)
```
This is working for me after the update. Pre-v1.0.3 will upload, but not reload.

**Comment by gregorskii** [comment]
Confirmed version 1.0.4 will return the stream.

Thank you!
